[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root --no-audit --no-fund"]

[start]
cmd = "echo override in railway.json startCommand"
